### ISSUE TITLE
Default value support

### ISSUE THREAD

**Issue by CptGuo** [sonalake/utah-parser#14]
Hello
Can < value /> element support default-value? if rule return empty string.
example:

<value id="id1" **defaultValue="value1"**><![CDATA[some rule]]></value>

<values>
        <value id="numberField" defaultValue="value1"><![CDATA[Some ID: {numbers}]]></value>
        <value id="stringFieldA" defaultValue="value1"><![CDATA[Some text: {stringToEOL}]]></value>
    </values>

**Comment by daniel-bray-sonalake** [comment]
It's not a feature we needed, but I can see how it'd be useful.

This is an open-source project, so please feel free to issue a PR to add this, and we'll review and merge it once it's tested.

Most of the magic happens in here: https://github.com/sonalake/utah-parser/blob/master/src/main/java/com/sonalake/utah/config/Config.java#L104

You'd just need to decide whether the default should be used if there's no match, or if it should also be used if the match returns an empty string.

**Comment by CptGuo** [comment]
3Q, i will to it myself.
PS: it's a good tool for me;

**Comment by daniel-bray-sonalake** [comment]
Glad to help!

**Comment by daniel-bray-sonalake** [comment]
This will be released in version 1.1.0
