### ISSUE TITLE
Streaming Support - exposing getters for "Config" protected variables

### ISSUE THREAD

**Issue by sgoeschl** [sonalake/utah-parser#18]
Hi @daniel-bray-sonalake - I am struggling a but how to generate a table view without eagerly parsing all records

* I embedded the parser in one of my pet projects
* I'm parsing XXX thousands of lines 
* I need to create a CSV file with ALL headers
* I would like to stream the results

Basically I see two options (apart from hard-coding the expected headers)

* Introduce a "default" value fiield so all headers are retained 
* Expose the protected variables

I think with exposing the protected variables the CLI could stream the CSV as well? What do you think?

Thanks in advance, 

Siegfried Goeschl

**Comment by daniel-bray-sonalake** [comment]
@sgoeschl this is available on develop, and will be present in the 1.1.0 release when we ship it, shortly.

See   [public List<String> Config.getHeaderNames()](https://github.com/sonalake/utah-parser/blob/master/src/main/java/com/sonalake/utah/config/Config.java#L187)

**Comment by sgoeschl** [comment]
Looks good to me :)
