### ISSUE TITLE
Parse records from same file that are slightly different

### ISSUE THREAD

**Issue by ctataryn** [sonalake/utah-parser#4]
I was wondering if Utah is capable of parsing a file that has fields that are positioned differently depending on the presence of other fields. For example:

````
DEC 15 DEC 17 ACME CORP USA
55134425350800130124929

$21.00

DEC 18 DEC 21 DELICIOUS RESTRO
55181365352461656841475

$49.71

DEC 21 DEC 23 ONLINE SERVICE CO
55541865356004056383845

Foreign Currency-USD 20.99 Exchange rate-1.430204

$30.02

````

The format is:

````
<TX DATE> <DATE POSTED> <VENDOR>
<TXID>

[TX AMT **-or-** Foreign TX AMT]

[TX AMT **-or-** start of new record]
````

It is a list of credit card line items where the TX AMOUNT (transaction amount) may show up on the 4th line, or instead the 4th line might contain details about foreign exchange amounts.  If it is details about foreign exchange, then the TX AMOUNT will show up on the 6th line

My hope is I'll be able to capture the <TX DATE>, <VENDOR>, <TX AMT> and <Foreign TX AMT> (when applicable).

**Comment by daniel-bray-sonalake** [comment]
It should be possible, in this example here we pull the value from different places, depending on the shape of the record, you might be able to do something like this:

https://github.com/sonalake/utah-parser/#example-3-file-with-multiple-delimiters

**Comment by daniel-bray-sonalake** [comment]
Do you need the foreign tax amount for this, or just the tax amount?

``````

**Comment by daniel-bray-sonalake** [comment]
If we're to ignore the foreign tax amount, and just use the underlying tax amount, this should work:

```xml
<config>
    <searches>
        <search id="QUERY-LINE"><![CDATA[({sdate})\s({sdate})\s({company})]]></search>
		<search id="sdate"><![CDATA[\S{3} \d{2}]]></search>
		<search id="company"><![CDATA[[\S ]+]]></search>
		<!-- I'm assuming the txit is 23 characters of digits -->
		<search id="txid"><![CDATA[(\d{23})]]></search>
		<search id="taxAmount"><![CDATA[\$(\d{1,2}\.\d{1,2})]]></search>
    </searches>
    <!-- the record delimiter is at the start of the line -->
    <delim at-start="true">^{QUERY-LINE}</delim>

    <values>
        <!-- pull the values we want from the delimiter -->
        <value id="txDate" group="1"><![CDATA[{QUERY-LINE}]]></value>
        <value id="postedDate" group="2"><![CDATA[{QUERY-LINE}]]></value>
        <value id="vendor" group="3"><![CDATA[{QUERY-LINE}]]></value>
		<!-- pull the transaction id and tax amount from the rest of the record -->
		<value id="txid" group="1"><![CDATA[{txid}]]></value>
		<value id="taxAmount" group="1"><![CDATA[{taxAmount}]]></value>
    </values>
</config>
```


I tried this with the records you supplied and got these results, is this what you're after?

`cat sample.txt | java -jar ..\target\utah-parser-cli-1.0.2-SNAPSHOT.jar -f config.xml -o json`

```json
[
  {
    "postedDate": "DEC 17",
    "taxAmount": "21.00",
    "txDate": "DEC 15",
    "txid": "55134425350800130124929",
    "vendor": "ACME CORP USA"
  },
  {
    "postedDate": "DEC 21",
    "taxAmount": "49.71",
    "txDate": "DEC 18",
    "txid": "55181365352461656841475",
    "vendor": "DELICIOUS RESTRO"
  },
  {
    "postedDate": "DEC 23",
    "taxAmount": "30.02",
    "txDate": "DEC 21",
    "txid": "55541865356004056383845",
    "vendor": "ONLINE SERVICE CO"
  }
]
```

**Comment by ctataryn** [comment]
Thanks so much for putting together an example parser.  Unfortunately, yes, I need to track that foreign amount.  To provide some context, these records represent credit card transactions, and when you see that Foreign Amount line it means that a charge was made in a foreign currency.  It is important to track both the amount of the transaction in the foreign currency as well as the amount the credit card company charges in the home currency such that the "markup" can be accounted for as a "fee". That being said the Foreign Amount line also contains an Exchange Rate which could be tracked instead of the Foreign Amount.

Ultimately these values go into a spreadsheet with the following columns:

````
DATE, VENDOR, AMOUNT, AMOUNT_FOREIGN
````

**Comment by ctataryn** [comment]
And I'm pretty sure, since the parser won't fail if a value isn't present, I can simply add another pattern to capture the foreign amount using your configuration as my template. I'll report back!

**Comment by ctataryn** [comment]
Bingo! Added:

```
<config>
  <searches>
    <!-- ... -->
    <search id="txFAmount"><![CDATA[Foreign Currency-USD (\d+\.\d{1,2})]]></search>
  </searches>
  <values>
    <!-- ... -->
    <value id="txFAmount" group="1"><![CDATA[{txFAmount}]]></value>
  </values>
</config>

```
And it worked like a charm. Thanks again.

**Comment by daniel-bray-sonalake** [comment]
We aim to please ;)
