### ISSUE TITLE
Parsing complex structure

### ISSUE THREAD

**Issue by hendriklenz** [sonalake/utah-parser#6]
Hi, i try to parse an complex text structure with the great utah parser. But ihave some trouble to get the records. 

I have an example here (example.txt) and i will get this result:

KTO,KUNDENNAME,LFD.NR,DATUM,VR-NETKEY,HERKUNFT
11111111,Record 1,1082,28.08.16,9100000001586068776,INTB-TAN 074957
22222222,Record 2,666,29.08.16,9100000000615483624,INTB-TAN 643536

Have you some tipps for me and is it possible withe the utah parser?

Thanks
Hendrik

[example.txt](https://github.com/sonalake/utah-parser/files/471601/example.txt)

**Comment by daniel-bray-sonalake** [comment]
I'm afraid UTAH only supports records split by a single delimiter - in this case it looks like some of these fields come from three different places

The initial section with lines like this 
`  11111111   Record 1               SEPA-EINZELLAST        1082                                             1              13,00 EUR`

Then two more sections, with lines like this 
`28.08.16 23:34:37,44   9100000001586068776   Record 1                                          E`

and

`INTB-TAN 074957       Record 1`

Where we'd need to use the `Record n` field to link them together.

UTAH isn't geared-up for this kind of multiple-pass parsing, sorry
